# Generated by Django 4.1 on 2022-08-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JSError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('timestamp', models.BigIntegerField()),
                ('full_ua', models.TextField()),
                ('browser_name', models.TextField()),
                ('browse_version', models.TextField()),
                ('os', models.TextField()),
                ('message', models.TextField()),
                ('position', models.TextField()),
                ('stack', models.TextField()),
                ('selector', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromiseError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('timestamp', models.BigIntegerField()),
                ('full_ua', models.TextField()),
                ('browser_name', models.TextField()),
                ('browse_version', models.TextField()),
                ('os', models.TextField()),
                ('message', models.TextField()),
                ('stack', models.TextField()),
                ('selector', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('timestamp', models.BigIntegerField()),
                ('full_ua', models.TextField()),
                ('browser_name', models.TextField()),
                ('browse_version', models.TextField()),
                ('os', models.TextField()),
                ('message', models.TextField()),
                ('filename', models.TextField()),
                ('tag_name', models.TextField()),
                ('position', models.TextField()),
                ('selector', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhiteScreenError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('timestamp', models.BigIntegerField()),
                ('full_ua', models.TextField()),
                ('browser_name', models.TextField()),
                ('browse_version', models.TextField()),
                ('os', models.TextField()),
                ('message', models.TextField()),
                ('empty_points', models.TextField()),
                ('screen', models.TextField()),
                ('view_point', models.TextField()),
                ('selector', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='XhrError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('timestamp', models.BigIntegerField()),
                ('full_ua', models.TextField()),
                ('browser_name', models.TextField()),
                ('browse_version', models.TextField()),
                ('os', models.TextField()),
                ('message', models.TextField()),
                ('status', models.TextField()),
                ('duration', models.IntegerField()),
                ('response', models.TextField()),
                ('params', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
