# Generated by Django 4.1 on 2022-08-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceerror',
            name='position',
        ),
        migrations.RemoveField(
            model_name='whitescreenerror',
            name='message',
        ),
    ]
