# Generated by Django 4.1 on 2022-08-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='connect',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='dns',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='dom_content_loaded',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='dom_ready',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='first_content_paint',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='first_meaningful_paint',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='first_paint',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='largest_contentful_paint',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='load',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='parse_dom',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='response',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='to_interactive',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='ttfb',
            field=models.FloatField(),
        ),
    ]
