# Generated by Django 4.1 on 2022-08-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField()),
                ('from_ip', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('timestamp', models.BigIntegerField()),
                ('full_ua', models.TextField()),
                ('browser_name', models.TextField()),
                ('browse_version', models.TextField()),
                ('os', models.TextField()),
                ('dns', models.DecimalField(decimal_places=3, max_digits=10)),
                ('connect', models.DecimalField(decimal_places=3, max_digits=10)),
                ('response', models.DecimalField(decimal_places=3, max_digits=10)),
                ('parse_dom', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dom_ready', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ttfb', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dom_content_loaded', models.DecimalField(decimal_places=3, max_digits=10)),
                ('to_interactive', models.DecimalField(decimal_places=3, max_digits=10)),
                ('load', models.DecimalField(decimal_places=3, max_digits=10)),
                ('first_paint', models.DecimalField(decimal_places=3, max_digits=10)),
                ('first_content_paint', models.DecimalField(decimal_places=3, max_digits=10)),
                ('first_meaningful_paint', models.DecimalField(decimal_places=3, max_digits=10)),
                ('largest_contentful_paint', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
