# Generated by Django 4.1 on 2022-08-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_err'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='err',
            name='type',
        ),
        migrations.AlterField(
            model_name='err',
            name='browse_version',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='err',
            name='browser_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='err',
            name='error_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='err',
            name='full_ua',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='err',
            name='kind',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='err',
            name='os',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='err',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
