# Generated by Django 4.1 on 2022-08-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_resourceerror_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='ip',
            field=models.TextField(default='127.0.0.1'),
        ),
        migrations.AddField(
            model_name='duration',
            name='start_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pv',
            name='ip',
            field=models.TextField(default='127.0.0.1'),
        ),
    ]
