# Generated by Django 4.1 on 2022-08-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('domain', models.TextField(primary_key=True, serialize=False)),
                ('create_time', models.BigIntegerField()),
            ],
        ),
    ]
