# Generated by Django 4.1 on 2022-08-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_performance_connect_alter_performance_dns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='website',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
